[package]
name = "ag-rs-consul"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
rs-consul = "0.5.0"
async-trait = "0.1.77"